import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    // Must be its own top-level config object with ONLY `ignores` — ESLint's
    // flat config treats that shape as global, applying before anything
    // else, whereas a trailing `ignores` combined with other keys (as
    // originally written here) only scoped to that one object and left
    // .next/ + project/'s prototype tooling getting linted as if they were
    // app source (7938 problems, almost all from bundled/vendored .next/*.js).
    ignores: [
      ".next/**",
      "node_modules/**",
      "e2e-output/**",
      "prisma/migrations/**",
      // Doc-tooling prototype (PRD/architecture .dc.html support scripts,
      // not part of the Next.js app) — see project/CLAUDE.md.
      "project/**",
      // Autogenerated by `next dev`/`next build`, regenerated every run —
      // not source to lint or hand-edit.
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
